# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    lock: '%env(LOCK_DSN)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host' ]
    rate_limiter:
        popup_limits:
            policy: 'fixed_window'
            limit: 100
            interval: '1 minute'

    http_client:
        default_options:
            verify_peer: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
